# -*- coding: utf-8 -*-
"""LangDetectTrans.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1shSYeRW6sMbVxLCzK9gC-Xhrbm8LnRaC
"""

"""
LangDetectTrans v0.1

Script to detect language and translate texts to English using MariantMT models, able to
work on a great set of languages. Models can be reviewed on the Hugging Face webpage:

https://huggingface.co/Helsinki-NLP

For this script to properly work, 'transformers', 'torch' and 'pycld3' modules must be installed

pip install -q transformers
pip install -q torch
pip install -q textblob

Translation example:

text = 'Hola me llamo Camilo'
print(translate_to_english(text))

>> Out: ["Hey, my name's Camilo."]
"""

from transformers import MarianTokenizer, MarianMTModel
import torch
from textblob import TextBlob

# check if gpu is available
device = torch.device("cuda" if torch.cuda.is_available() else "cpu")

def detect_lang(text):
  """Language detection using TextBlob"""
  lang = TextBlob(text)
  source_lang = str(lang.detect_language())

  return source_lang

def get_lang_group(source_lang):
  """Classifies detected language into one
  of the pretrained multilingual models"""

  gp = source_lang
  
  GROUP_MEMBERS = {
  'ZH': ['cmn', 'cn', 'yue', 'ze_zh', 'zh_cn', 'zh_CN', 'zh_HK', 'zh_tw', 'zh_TW', 'zh_yue', 'zhs', 'zht', 'zh'],
  'ROMANCE': ['fr', 'fr_BE', 'fr_CA', 'fr_FR', 'wa', 'frp', 'oc', 'ca', 'rm', 'lld', 'fur', 'lij', 'lmo', 'es', 'es_AR', 'es_CL', 'es_CO', 'es_CR', 'es_DO', 'es_EC', 'es_ES', 'es_GT', 'es_HN', 'es_MX', 'es_NI', 'es_PA', 'es_PE', 'es_PR', 'es_SV', 'es_UY', 'es_VE', 'pt', 'pt_br', 'pt_BR', 'pt_PT', 'gl', 'lad', 'an', 'mwl', 'it', 'it_IT', 'co', 'nap', 'scn', 'vec', 'sc', 'ro', 'la'],
  'NORTH_EU': ['de', 'nl', 'fy', 'af', 'da', 'fo', 'is', 'no', 'nb', 'nn', 'sv'],
  'SCANDINAVIA': ['da', 'fo', 'is', 'no', 'nb', 'nn', 'sv'],
  'SAMI': ['se', 'sma', 'smj', 'smn', 'sms'],
  'NORWAY': ['nb_NO', 'nb', 'nn_NO', 'nn', 'nog', 'no_nb', 'no'],
  'CELTIC': ['ga', 'cy', 'br', 'gd', 'kw', 'gv']
  }
  
  for group, lang_list in GROUP_MEMBERS.items():
    for lang in lang_list:
      if lang == source_lang:
        gp = group
        break

  return gp

def translate_to_english(text): #Translation function
  """Detects language, and uses pretrained models 
  to translate them into english"""

  source_lang = detect_lang(text)    
  model_name = f'Helsinki-NLP/opus-mt-{get_lang_group(source_lang)}-{"en"}'
 
  model = MarianMTModel.from_pretrained(model_name)               #Loads the MarianMT model
  model.to(device)                                                #Send model to gpu
  tokenizer = MarianTokenizer.from_pretrained(model_name)         #Text to tokens
  batch = tokenizer.prepare_seq2seq_batch(src_texts=[text])       #Creates word batches for the sequential passing to the model
  batch.to(device)                                                #Send batch to gpu
  generate_model = model.generate(**batch)  
  translation = tokenizer.batch_decode(generate_model, skip_special_tokens=True)
  
  return translation